#!/bin/bash
# Between-deploys watchdog for /health/deep.
#
# A 200 from /health/live or even /health/ready does not mean payments are
# being detected — the process can be up while evmmonitor's data is stale or
# an RPC has gone quiet, and every HTTP-status-only check stays green through
# that. This fetches /health/deep, parses the body, and fails on the fields
# that actually reflect the money path:
#   - non-200 or no response
#   - monitor.data_fresh false
#   - any rpcs.*.status not "ok"
#   - postgres or redis not "ok"
#
# Meant to run on a schedule from somewhere that is not the deploy host, so a
# dead box cannot also be the thing reporting it is fine. Single-shot, not a
# poll loop: health-gate.sh already owns "wait for it to come back after a
# deploy". This owns "notice it stopped between deploys".
#
# Required env vars:
#   HEALTH_URL       — full URL to the /health/deep endpoint
#
# Optional:
#   SENTRY_CRON_URL  — Sentry Cron Monitor check-in URL (as generated by
#                      Sentry for "check in via HTTP"). ?status=ok/error is
#                      appended. Skipped if unset, so this still works as a
#                      plain pass/fail check without Sentry configured.

set -u
set -o pipefail

: "${HEALTH_URL:?HEALTH_URL required — e.g. https://testnet.random.cash/api/health/deep}"
: "${SENTRY_CRON_URL:=}"

log() { printf '[check-health-deep] %s\n' "$*"; }

checkin() {
  local status="$1"
  [ -n "$SENTRY_CRON_URL" ] || return 0
  curl -fsS -m 10 --retry 3 -o /dev/null "${SENTRY_CRON_URL}?status=${status}" \
    || log "Sentry check-in failed (status=${status})"
}

BODY=$(curl -sS --max-time 10 "$HEALTH_URL" 2>&1)
CURL_EXIT=$?
if [[ $CURL_EXIT -ne 0 ]]; then
  log "FAIL: no response from $HEALTH_URL (curl exit $CURL_EXIT)"
  checkin error
  exit 1
fi

PG_STATUS=$(echo "$BODY" | python3 -c "import json,sys; print(json.load(sys.stdin)['postgres']['status'])" 2>/dev/null || echo "error")
REDIS_STATUS=$(echo "$BODY" | python3 -c "import json,sys; print(json.load(sys.stdin)['redis']['status'])" 2>/dev/null || echo "error")
MONITOR_FRESH=$(echo "$BODY" | python3 -c "import json,sys; print(json.load(sys.stdin)['monitor']['data_fresh'])" 2>/dev/null || echo "False")
RPC_BAD=$(echo "$BODY" | python3 -c "
import json, sys
data = json.load(sys.stdin)
bad = [k for k, v in data.get('rpcs', {}).items() if v.get('status') != 'ok']
print(','.join(bad) if bad else '')
" 2>/dev/null || echo "unknown")

FAILED=()
[[ "$PG_STATUS" == "ok" ]] || FAILED+=("postgres=$PG_STATUS")
[[ "$REDIS_STATUS" == "ok" ]] || FAILED+=("redis=$REDIS_STATUS")
[[ "$MONITOR_FRESH" == "True" ]] || FAILED+=("monitor.data_fresh=$MONITOR_FRESH")
[[ -z "$RPC_BAD" ]] || FAILED+=("unhealthy chains: $RPC_BAD")

if [[ ${#FAILED[@]} -gt 0 ]]; then
  log "FAIL: ${FAILED[*]}"
  checkin error
  exit 1
fi

log "HEALTHY — pg=ok redis=ok monitor.data_fresh=true rpcs=all_ok"
checkin ok
