#!/bin/bash
# Between-deploys watchdog for /health/deep.
#
# A 200 from /health/live or even /health/ready does not mean payments are
# being detected — the process can be up while evmmonitor's data is stale or
# an RPC has gone quiet, and every HTTP-status-only check stays green through
# that. This fetches /health/deep, parses the body, and fails on the fields
# that actually reflect the money path:
#   - non-200 or no response
#   - monitor.data_fresh false
#   - any rpcs.*.status not "ok"
#   - a chain's rpcs.*.last_block unchanged across several consecutive checks
#     (a chain can report status "ok" while its indexer has stopped advancing
#     — a distinct partial-outage mode from monitor.data_fresh going false)
#   - postgres or redis not "ok"
#
# Meant to run on a schedule from somewhere that is not the deploy host, so a
# dead box cannot also be the thing reporting it is fine. Single-shot, not a
# poll loop: health-gate.sh already owns "wait for it to come back after a
# deploy". This owns "notice it stopped between deploys".
#
# Required env vars:
#   HEALTH_URL        — full URL to the /health/deep endpoint
#
# Optional:
#   SENTRY_CRON_URL    — Sentry Cron Monitor check-in URL (as generated by
#                        Sentry for "check in via HTTP"). ?status=ok/error is
#                        appended. Skipped if unset, so this still works as a
#                        plain pass/fail check without Sentry configured.
#   HEALTH_STATE_FILE  — path to a JSON file this script reads and rewrites
#                        each run, tracking last_block per chain across
#                        invocations. A GitHub Actions run starts from a fresh
#                        checkout with nothing else persisted, so the caller
#                        is expected to restore this file from a cache before
#                        running and save it back after (see
#                        health-monitor.yml). Stall detection is skipped if
#                        this is unset.
#   STALL_THRESHOLD    — number of consecutive checks a chain's last_block
#                        may repeat before it counts as stalled. Default 3.

set -u
set -o pipefail

: "${HEALTH_URL:?HEALTH_URL required — e.g. https://testnet.random.cash/api/health/deep}"
: "${SENTRY_CRON_URL:=}"
: "${HEALTH_STATE_FILE:=}"
: "${STALL_THRESHOLD:=3}"

log() { printf '[check-health-deep] %s\n' "$*"; }

checkin() {
  local status="$1"
  [ -n "$SENTRY_CRON_URL" ] || return 0
  curl -fsS -m 10 --retry 3 -o /dev/null "${SENTRY_CRON_URL}?status=${status}" \
    || log "Sentry check-in failed (status=${status})"
}

RESPONSE=$(curl -sS --max-time 10 -w '\n%{http_code}' "$HEALTH_URL" 2>&1)
CURL_EXIT=$?
if [[ $CURL_EXIT -ne 0 ]]; then
  log "FAIL: no response from $HEALTH_URL (curl exit $CURL_EXIT)"
  checkin error
  exit 1
fi

HTTP_CODE=$(printf '%s' "$RESPONSE" | tail -n1)
BODY=$(printf '%s' "$RESPONSE" | sed '$d')
if [[ "$HTTP_CODE" != "200" ]]; then
  log "FAIL: $HEALTH_URL returned HTTP $HTTP_CODE"
  checkin error
  exit 1
fi

PG_STATUS=$(echo "$BODY" | python3 -c "import json,sys; print(json.load(sys.stdin)['postgres']['status'])" 2>/dev/null || echo "error")
REDIS_STATUS=$(echo "$BODY" | python3 -c "import json,sys; print(json.load(sys.stdin)['redis']['status'])" 2>/dev/null || echo "error")
MONITOR_FRESH=$(echo "$BODY" | python3 -c "import json,sys; print(json.load(sys.stdin)['monitor']['data_fresh'])" 2>/dev/null || echo "False")
RPC_BAD=$(echo "$BODY" | python3 -c "
import json, sys
data = json.load(sys.stdin)
bad = [k for k, v in data.get('rpcs', {}).items() if v.get('status') != 'ok']
print(','.join(bad) if bad else '')
" 2>/dev/null || echo "unknown")

STALL_BAD=""
if [[ -n "$HEALTH_STATE_FILE" ]]; then
  STALL_BAD=$(HEALTH_BODY="$BODY" python3 - "$HEALTH_STATE_FILE" "$STALL_THRESHOLD" <<'PYEOF' 2>/dev/null || echo "unknown"
import json, os, sys

body = json.loads(os.environ["HEALTH_BODY"])
state_path, threshold = sys.argv[1], int(sys.argv[2])

prev = {}
if os.path.exists(state_path):
    try:
        with open(state_path) as f:
            prev = json.load(f)
    except (json.JSONDecodeError, OSError):
        prev = {}

stalled = []
state = {}
for chain, info in body.get("rpcs", {}).items():
    last_block = info.get("last_block")
    if last_block is None:
        continue
    prev_chain = prev.get(chain, {})
    if prev_chain.get("last_block") == last_block:
        count = prev_chain.get("unchanged_count", 0) + 1
    else:
        count = 1
    state[chain] = {"last_block": last_block, "unchanged_count": count}
    if count > threshold:
        stalled.append(f"{chain} (last_block={last_block} unchanged x{count})")

os.makedirs(os.path.dirname(state_path) or ".", exist_ok=True)
with open(state_path, "w") as f:
    json.dump(state, f)

print(",".join(stalled))
PYEOF
)
fi

FAILED=()
[[ "$PG_STATUS" == "ok" ]] || FAILED+=("postgres=$PG_STATUS")
[[ "$REDIS_STATUS" == "ok" ]] || FAILED+=("redis=$REDIS_STATUS")
[[ "$MONITOR_FRESH" == "True" ]] || FAILED+=("monitor.data_fresh=$MONITOR_FRESH")
[[ -z "$RPC_BAD" ]] || FAILED+=("unhealthy chains: $RPC_BAD")
[[ -z "$STALL_BAD" || "$STALL_BAD" == "unknown" ]] || FAILED+=("stalled last_block: $STALL_BAD")

if [[ ${#FAILED[@]} -gt 0 ]]; then
  log "FAIL: ${FAILED[*]}"
  checkin error
  exit 1
fi

log "HEALTHY — pg=ok redis=ok monitor.data_fresh=true rpcs=all_ok"
checkin ok
