#!/usr/bin/env bash
# Manage which payserver-commons this checkout builds against.
#
# The workspace pins commons by revision in the root Cargo.toml, so a build is
# reproducible from the repo alone. That is deliberately inconvenient for
# someone editing commons and this repo together, which is what `link` is for:
# it writes an UNCOMMITTED .cargo/config.toml patching the crates to a local
# path. Cargo honours [patch] in config files, so the committed manifest stays
# pinned while your working copy builds against your checkout.
#
#   scripts/commons.sh link [path]   build against a local checkout (default: sibling)
#   scripts/commons.sh unlink        go back to the pinned revision
#   scripts/commons.sh status        show the pin and whether a link is active
#   scripts/commons.sh pin <rev>     move the pin; `main` resolves to origin/main
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
manifest="$repo_root/Cargo.toml"
config="$repo_root/.cargo/config.toml"
url="https://github.com/randomcash/payserver-commons.git"
crates=(types auth crypto rates ui-kit)

die() { echo "error: $*" >&2; exit 1; }
current_rev() { grep -m1 -oP 'rev = "\K[0-9a-f]{40}' "$manifest" || true; }

case "${1:-status}" in
  link)
    path="${2:-$(dirname "$repo_root")/payserver-commons}"
    [ -d "$path" ] || die "no commons checkout at $path"
    path="$(cd "$path" && pwd)"   # absolute, so it survives any cwd
    mkdir -p "$(dirname "$config")"
    {
      echo "# Generated by scripts/commons.sh - not committed."
      echo "# Build against a local commons checkout while the manifest stays pinned."
      echo "# Remove with: scripts/commons.sh unlink"
      echo
      echo "[patch.\"$url\"]"
      for c in "${crates[@]}"; do echo "$c = { path = \"$path/$c\" }"; done
    } > "$config"
    # Resolving under the patch rewrites Cargo.lock's commons entries to the
    # local path form. That is fine locally and must never be committed - it
    # would undo the pin for everyone. Restore it on unlink, and say so now.
    cargo metadata --format-version 1 >/dev/null 2>&1 || true
    echo "linked → $path"
    echo
    echo "NOTE: Cargo.lock now points at that path instead of the pinned revision."
    echo "      Do not commit it. 'scripts/commons.sh unlink' puts it back."
    ;;
  unlink)
    [ -f "$config" ] || { echo "not linked"; exit 0; }
    rm -f "$config"; rmdir "$(dirname "$config")" 2>/dev/null || true
    # Re-resolve so Cargo.lock records the pinned revision again rather than the
    # path form the link left behind. Without this, unlinking looks clean while
    # the lock still says something else.
    echo "restoring Cargo.lock to the pinned revision..."
    # `cargo metadata` re-resolves and rewrites the lock; `cargo update -p` cannot
    # be used here because the patched entries carry no git source to match on.
    ( cd "$repo_root" && cargo metadata --format-version 1 >/dev/null 2>&1 ) || true
    echo "unlinked - building against the pinned revision again"
    ;;
  status)
    rev="$(current_rev)"
    echo "pinned rev : ${rev:-<none found>}"
    if [ -f "$config" ]; then
      echo "local link : ACTIVE → $(grep -m1 -oP 'path = "\K[^"]+' "$config" | xargs dirname)"
      echo "             builds here do NOT use the pin above"
    else
      echo "local link : none"
    fi
    ;;
  pin)
    rev="${2:?usage: commons.sh pin <rev|main>}"
    sibling="$(dirname "$repo_root")/payserver-commons"
    if [ "$rev" = main ]; then
      [ -d "$sibling" ] || die "need a commons checkout at $sibling to resolve 'main'"
      git -C "$sibling" fetch -q origin
      rev="$(git -C "$sibling" rev-parse origin/main)"
    fi
    [[ "$rev" =~ ^[0-9a-f]{40}$ ]] || die "expected a full 40-char sha, got '$rev'"
    old="$(current_rev)"
    [ "$rev" = "$old" ] && { echo "already pinned to $rev"; exit 0; }
    sed -i "s/rev = \"$old\"/rev = \"$rev\"/g" "$manifest"
    echo "pinned $old → $rev"
    echo "run 'cargo update -p types -p auth -p crypto -p rates -p ui-kit' then commit Cargo.toml and Cargo.lock"
    ;;
  -h|--help) sed -n '2,15p' "${BASH_SOURCE[0]}" | sed 's/^# \?//' ;;
  *) die "unknown command '${1}' (link|unlink|status|pin)" ;;
esac
