-- A plain "read undispatched rows" drain (the previous migration's shape)
-- has no way to stop two drain instances - this codebase runs more than one
-- for availability - from both reading and acting on the same obligation:
-- nothing marks a row as being worked on until *after* delivery is attempted,
-- so two instances polling their own timers can both queue the same webhook.
--
-- `claimed_until` gives the drain a visibility deadline, the same shape the
-- webhook delivery queue's own claim already uses: claiming an obligation
-- sets this to a near-future time, and only a row with no claim or an
-- expired one is
-- eligible to be claimed again (`SELECT ... FOR UPDATE SKIP LOCKED`, so two
-- claimants racing the same query never pick the same row). A claimant that
-- dies mid-dispatch without marking the obligation dispatched leaves it
-- reclaimable once the deadline passes, rather than lost or duplicated.
ALTER TABLE webhook_outbox ADD COLUMN claimed_until TIMESTAMPTZ;
